#!/bin/bash
# USAGE: ./jarexec <target-jar> <binary-name>
# EXAMPLE: ./jarexec minecraft.jar minecraft.sh

TARGET_FILE=$(base64 -w 0 $1)
echo "
JAR_FILE=\"$(printf $TARGET_FILE)\"
printf \$JAR_FILE | base64 -d > .pretend_like_you_never_saw_me.jar
java -jar .pretend_like_you_never_saw_me.jar; rm .pretend_like_you_never_saw_me.jar
" > $2
chmod +x $2
